project_id = "wattbridge"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://wattbridge.vercel.app"
additional_redirect_urls = ["http://localhost:3000/dashboard", "http://localhost:3000/auth/callback", "https://wattbridge.vercel.app/dashboard", "https://wattbridge.vercel.app/auth/callback"]
jwt_expiry = 3600
enable_signup = true

[db]
port = 54322
major_version = 17
